title: Join-MlOps-Journey
author:
  name: vsatyakiran
  email: vantakulasatyakiran@gmail.com
description: Join the MLOps Journey to learn about the latest trends in MLOps, DevOps, DataOps, and AI/ML. 
  We will discuss the best practices, tools, and technologies that are shaping the future of AI/ML.
  We will also discuss the challenges and solutions in deploying AI/ML models in production.
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md


   - { platform: github,         user_url: "https://github.com/vsatyakiran" }
   - { platform: linkedin,       user_url: "https://linkedin.com/in/vantakula-satya-kiran-165536251" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

